name: build

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - uses: goreleaser/goreleaser-action@v7
        with:
          # https://github.com/goreleaser/goreleaser/releases/tag/v2.18.2
          version: v2.18.2
          args: build --clean --snapshot

      - shell: sh
        run: ./dist/krf_linux_amd64_v1/krf --version

      - uses: actions/upload-artifact@v7
        continue-on-error: true
        with:
          name: artifacts
          path: dist/
          retention-days: 1

  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - uses: autero1/action-gotestsum@v2.0.0
        with:
          # https://github.com/gotestyourself/gotestsum/releases/tag/v1.13.0
          gotestsum_version: 1.13.0

      - shell: sh
        run: gotestsum --format testname ./...
